name: Composite

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-composite:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: ./.github/actions/greet_someone
        with:
          who-to-greet: 'Person'
      - name: Conitional step
        if: ${{ steps.setoutput.outputs.input == 'Person'}}
        run: echo "Test"