name: Composite

on:
  push:
    branches:
      - main

jobs:
  run-composite:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: ./.github/actions/greet_someone@5fb4a31
        with:
          who-to-greet: 'Test person'