name: Badges

on:
  push:
    branches:
      - main

jobs:
  replace_badge_failed:
    runs-on: ubuntu-latest
    name: Replace badge to failed
    steps:
      - uses: actions/checkout@v4
      - name: Change url
        run: |
          sed -i "s/<badge>/tests-failed-red/" README.md
          git config user.email "toon.dubois@gmail.com"
          git config user.name "GewoonToon"
          git commit -am "Automated report"
          git push
        shell: bash